version: 0.0
Resources:
- TargetService:
    Type: AWS::ECS::Service
    properties:
      TaskDefinition: "arn:aws:ecs:ap-south-1:528302462811:task-definition/flask-app"
      LoadBalancerInfo:
        ContainerName: "flask"
        ContainerPort: 5000
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: ["subnet-00dd9e07cb46b87f7", "subnet-00517204282a7b5e2"]
          SecurityGroups: ["sg-04e48081f407bc792"]
          # AssignPublicIp: "ENABLED"